### ISSUE TITLE
Error after upgrading apispec

### ISSUE THREAD

**Issue by scorp10n-6** [colibris-framework/colibris#43]
Hi,
I've had to recreate the pipenv for a project today, and after reinstalling all the packages from Pipfile, I get this error when I try to run the project : 

2019-09-23 13:52:57:   DEBUG: [colibris.conf.backends] AuthenticationBackend: using class colibris.authentication.jwt.JWTBackend
2019-09-23 13:52:57:   DEBUG: [colibris.conf.backends] AuthorizationBackend: using class colibris.authorization.role.RoleBackend
2019-09-23 13:52:57:   DEBUG: [colibris.conf.backends] DatabaseBackend: using class colibris.persist.PostgreSQLBackend
2019-09-23 13:52:57:   DEBUG: [colibris.persist] db connection initialized
2019-09-23 13:52:57:   DEBUG: [asyncio] Using selector: SelectSelector
Traceback (most recent call last):
  File "E:/0Eclipse_Git/citi2zoho/citi2zoho/manage.py", line 11, in <module>
    main()
  File "E:/0Eclipse_Git/citi2zoho/citi2zoho/manage.py", line 7, in main
    commands.main()
  File "C:\Users\Geo\.virtualenvs\citi2zoho-hdmDLF8k\lib\site-packages\colibris\commands\__init__.py", line 59, in main
    exit_code = _command.run() or 0
  File "C:\Users\Geo\.virtualenvs\citi2zoho-hdmDLF8k\lib\site-packages\colibris\commands\base.py", line 26, in run
    return self.execute(options)
  File "C:\Users\Geo\.virtualenvs\citi2zoho-hdmDLF8k\lib\site-packages\colibris\commands\runserver.py", line 12, in execute
    web.run_app(app.get_web_app(), host=settings.LISTEN, port=settings.PORT)
  File "C:\Users\Geo\.virtualenvs\citi2zoho-hdmDLF8k\lib\site-packages\aiohttp\web.py", line 415, in run_app
    reuse_port=reuse_port))
  File "E:\Python_3\Lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "C:\Users\Geo\.virtualenvs\citi2zoho-hdmDLF8k\lib\site-packages\aiohttp\web.py", line 287, in _run_app
    await runner.setup()
  File "C:\Users\Geo\.virtualenvs\citi2zoho-hdmDLF8k\lib\site-packages\aiohttp\web_runner.py", line 203, in setup
    self._server = await self._make_server()
  File "C:\Users\Geo\.virtualenvs\citi2zoho-hdmDLF8k\lib\site-packages\aiohttp\web_runner.py", line 302, in _make_server
    await self._app.startup()
  File "C:\Users\Geo\.virtualenvs\citi2zoho-hdmDLF8k\lib\site-packages\aiohttp\web_app.py", line 389, in startup
    await self.on_startup.send(self)
  File "C:\Users\Geo\.virtualenvs\citi2zoho-hdmDLF8k\lib\site-packages\aiohttp\signals.py", line 34, in send
    await receiver(*args, **kwargs)  # type: ignore
  File "C:\Users\Geo\.virtualenvs\citi2zoho-hdmDLF8k\lib\site-packages\aiohttp_apispec\aiohttp_apispec.py", line 57, in doc_routes
    self._register(app_)
  File "C:\Users\Geo\.virtualenvs\citi2zoho-hdmDLF8k\lib\site-packages\aiohttp_apispec\aiohttp_apispec.py", line 91, in _register
    self._register_route(route, method, view)
  File "C:\Users\Geo\.virtualenvs\citi2zoho-hdmDLF8k\lib\site-packages\aiohttp_apispec\aiohttp_apispec.py", line 109, in _register_route
    self._update_paths(view.__apispec__, method, url_path)
  File "C:\Users\Geo\.virtualenvs\citi2zoho-hdmDLF8k\lib\site-packages\aiohttp_apispec\aiohttp_apispec.py", line 115, in _update_paths
    parameters = self.plugin.openapi.schema2parameters(
AttributeError: 'MarshmallowPlugin' object has no attribute 'openapi'

In the end I've downgraded the package apispec from 3.0.0 to version 2.0.2, apparently on the 2019-09-17, they've uploaded version 3.0.0

**Comment by lucifurtun** [comment]
Should be fixed in `0.9.0`.
